src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\FormTypeInterface;


/**
 * @ORM\Entity(repositoryClass=ItemRepository::class)
 */
class Item
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Name;

     /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Store;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Price = 0;

    /**
     * @ORM\Column(type="string", length=600, nullable=true)
     */
    private $Link;

    /**
     * @ORM\ManyToOne(targetEntity=Room::class, inversedBy="Items")
     * @ORM\JoinColumn(nullable=false, name="room_id", referencedColumnName="id")
     */
    private $Room;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    public function __construct()
    {
        $this->created = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(?string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(?float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->Link;
    }

    public function setLink(?string $Link): self
    {
        $this->Link = $Link;

        return $this;
    }

    public function getStore(): ?string
    {
        return $this->Store;
    }

    public function setStore(?string $Store): self
    {
        $this->Store = $Store;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->Room;
    }

    public function setRoom(?Room $Room): self
    {
        $this->Room = $Room;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Entity\User;
use App\Repository\ItemRepository;
use App\Repository\RoomRepository;
use App\Service\MailerService;
use Psr\Container\ContainerInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/{_locale}/user/login",
     * name="app_login",  methods={"GET", "POST"},
     * requirements={
     *         "_locale": "en|es",
     *     })
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('home_index');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    /**
     * @Route("/{_locale}/info/contact",
     * name="contact",
     * requirements={
     *         "_locale": "en|es",
     *     })
     */
    public function contact(
        Request $request,
        ContainerInterface $container,
        MailerService $mailerService
    ): Response {
        $response = '';

        if (strlen($request->request->get('email')) > 0) {
            $mail = $mailerService->initializeEmail($container);
            $mail->AddAddress('refactorhome@gmail.com', 'recipient-name');
            $mail->SetFrom('contact@homerefactor.com', 'Home Refactor');
            $mail->AddReplyTo($request->request->get('email'), 'Reply to');
            $mail->Subject = $request->request->get('subject');

            $content =
                '<p> Name: ' .
                $request->request->get('name') .
                '<p>' .
                '<p> Email: ' .
                $request->request->get('email') .
                '<p>' .
                '<p> Message: ' .
                $request->request->get('message') .
                '<p>';

            $mail->MsgHTML($content);

            if (!$mail->Send()) {
                $response =
                    '<div class="alert alert-danger text-center">The message was not sent.</div>';
            } else {
                $formFields = ['name', 'email', 'subject', 'agree'];

                foreach ($formFields as $field) {
                    $request->request->set($field, '');
                }

                $response =
                    '<div class="alert alert-success text-center">The message was sent.</div>';
            }
        }

        // $message = $mailerService->getHappyMessage();

        return $this->render('legal/contact.html.twig', [
            'message' => $response,
        ]);
    }

    /**
     * @Route("/user/{id}/delete", name="delete_user", methods={"GET"})
     */
    public function delete(
        User $userSelected,
        RoomRepository $roomRepository,
        ItemRepository $itemRepository,
        TokenStorageInterface $tokenStorage,
        Request $request
    ): Response {
        $user = $this->getUser();

        if ($user == null) {
            return $this->redirectToRoute('app_login');
        } elseif (
            $user->getId() != 1 &&
            $user->getId() != $userSelected->getId()
        ) {
            return $this->redirectToRoute('home_index');
        }

        $entityManager = $this->getDoctrine()->getManager();

        $rooms = $roomRepository->findByUserField(
            $userSelected->getId(),
            false
        );

        foreach ($rooms as $room) {
            $itemRepository->deleteByRoom($room);
        }

        $roomRepository->deleteByUser($userSelected->getId());
        $entityManager->flush();

        $entityManager->remove($userSelected);
        $entityManager->flush();

        if ($user->getId() == 1) {
            return $this->redirectToRoute('admin');
        } else {
            $tokenStorage->setToken(null);
            return $this->redirectToRoute('app_login');
        }
    }

    public function encodePassword($raw, $salt)
    {
        if (!in_array($this->algorithm, hash_algos(), true)) {
            throw new \LogicException(
                sprintf(
                    'The algorithm "%s" is not supported.',
                    $this->algorithm
                )
            );
        }

        //$salted = $this->mergePasswordAndSalt($raw, $salt);
        $salted = $salt . $raw;
        $digest = hash($this->algorithm, $salted, true);

        // "stretch" hash
        for ($i = 1; $i < $this->iterations; ++$i) {
            $digest = hash($this->algorithm, $digest . $salted, true);
        }

        return $this->encodeHashAsBase64
            ? base64_encode($digest)
            : bin2hex($digest);
    }

    /**
     * @Route("/{_locale}/user/logout",
     * name="app_logout",
     * requirements={
     *         "_locale": "en|es",
     *     })
     */
    public function logout()
    {
        // throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Admin{% endblock %}

{% block body %}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.jqueryui.min.css">
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.jqueryui.min.js"></script>

<form method="post">
    <div class="header">
        {# <img src="{{ absolute_url(asset('images/roof.jpg')) }}" class=""  alt="header"> #}
        <div class="container">
            <div class="home-header">
                <h1>
                    Admin    
                </h1>
            </div>
        </div>
    </div>


    <div class="content container panel panel-body">

    <nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="users-tab" data-toggle="tab" href="#users" role="tab" aria-controls="users" aria-selected="true">Users</a>
    <a class="nav-item nav-link" id="rooms-tab" data-toggle="tab" href="#rooms" role="tab" aria-controls="rooms" aria-selected="false">Rooms</a>
    <a class="nav-item nav-link" id="items-tab" data-toggle="tab" href="#items" role="tab" aria-controls="items" aria-selected="false">Items</a>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="users" role="tabpanel" aria-labelledby="users-tab">
    <table id="table_id" class="display">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Last login</th>    
                <th>Remove</th>                
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
                <td>
                {{ user.last|date("m/d/Y H:i", "Europe/Paris") }}
                </td>
                <td><a href="/user/{{user.id}}/delete">Remove</a></td>
            </tr>                
            {% endfor %}
        </tbody>
    </table>   
  </div>
  <div class="tab-pane fade" id="rooms" role="tabpanel" aria-labelledby="rooms-tab"><table id="rooms" class="display">
    <table id="table_id2" class="display">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>User Id</th>          
                <th>Items</th>     
                <th>Created</th>  
            </tr>
        </thead>
        <tbody>
            {% for room in rooms %}
            <tr>
                <td>{{ room.id }}</td>
                <td>{{ room.name }}</td>
                <td>{{ room.userId }}</td> 
                <td>    
                {% for item in room.items %}                
                    {{ item.id }}, 
                {% endfor %}      
                </td>
                <td>{{ room.created  |date("m/d/Y H:i", "Europe/Paris")}}</td>
            </tr>                
            {% endfor %}
        </tbody>
    </table>     
        
    </div>
  <div class="tab-pane fade" id="items" role="tabpanel" aria-labelledby="items-tab">
    <table id="table_id3" class="display">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Created</th>
                <th>Site</th>     
                <th>Room</th>
                <th>User Id</th>            
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{item.created |date("m/d/Y H:i", "Europe/Paris")}}</td>
                <td>{{ item.id }}</td>
                <td>{{ item.name }}</td>                
                <td><a href="{{item.link}}" target="_blank">{{ item.store }}</a></td>
                <td>{{ item.room.name }} | {{ item.room.id }}</td>     
                <td>{{ item.room.userid}}</td>
            </tr>                
            {% endfor %}
        </tbody>
    </table>   
  </div>
</div>
</form>

<script>
$(document).ready( function () {
    $('#table_id, #table_id2, #table_id3').DataTable();
} );

</script>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Refactor Home{% endblock %}

{% block body %}
<script src="https://www.google.com/recaptcha/api.js?render=reCAPTCHA_site_key"></script>
<form method="post">
    

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <div class="header">
        {# <img src="{{ absolute_url(asset('images/roof.jpg')) }}" class=""  alt="header"> #}
        <div class="container">
            <div class="home-header">
                <h1>
                    Sign In    
                </h1>
            </div>
        </div>
    </div>

    <div class="container  panel panel-body">
    {% if error %}
        <div class="alert alert-danger" style="top:0; margin-bottom: 0px; top: 15px;">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}
    </div>

    <div class="content container panel panel-body">

        <div class="field">
            <label for="inputEmail">Email</label>
            <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" required autofocus>   
        </div>

        <div class="field">
            <label for="inputPassword">Password</label>
            <input type="password" name="password" id="inputPassword" class="form-control" required>
        </div>
        

        <input type="hidden" name="_csrf_token"
            value="{{ csrf_token('authenticate') }}"
        >

        

        <div class="checkbox remember mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
        
        <div class="submit-button">
            <button class="g-recaptcha tn btn-lg btn-warning" 
                type="submit"
                data-sitekey="6Lc6BbEZAAAAACiI12d4emSiFKbBZWbaPCOG_ecn"
                data-callback='onSubmit' 
                data-action='submit'>Sign in</button>
            </button>
        </div>
        
    </div>
</form>

<script>
    function onSubmit(token) {
      $("form").submit();
    }
  </script>
{% endblock %}

templates/security/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %} Home Refactor | Profile{% endblock %}

{% block body %}

    <div class="header">
        {# <img src="{{ absolute_url(asset('images/roof.jpg')) }}" class=""  alt="header"> #}
        <div class="container">
            <div class="home-header">
                <h1>
                    {{ 'Profile'|trans({}, 'room') }}
                </h1>
            </div>
        </div>
    </div>

    <div class="content container panel panel-body">
    

        {{ form(form) }}

        <div class="actions">
            <a href="{{ path('delete_user', {id: user.id}) }}" class="btn btn-danger" id="delete_user"  onclick="return confirm_click();">
                {{ 'Delete Account'|trans({}, 'room') }}
            </a>
        </div>
        
    </div>

    <script>
    function confirm_click()
    {
        return confirm("{{ 'If you delete your account, all your data will be lost. Are you sure you want to proceed?'|trans({}, 'room') }}");
    }
    </script>


</form>
{% endblock %}